apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "smi-metrics.name" . }}
    helm.sh/chart: {{ include "smi-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "smi-metrics.fullname" . }}
data:
  config.yml: |
    {{- $files := .Files }}
    {{- if eq .Values.adapter "istio" }}
      {{- if .Values.default }}
        {{- $files.Get "default_istio.yaml" | nindent 4 -}}
      {{ else }}
        {{- $files.Get "istio.yaml" | nindent 4 -}}
      {{- end }}
    {{- else if eq .Values.adapter "linkerd" }}
      {{- $files.Get "linkerd.yaml" | nindent 4 -}}
    {{- end }}
    {{- .Values.config | toYaml | nindent 4 }}
