version: 2 
jobs:
  build: 
    docker: 
      - image: circleci/golang:1.12

    steps: 
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Dependencies
          command: |
            make dep
      - run:
          name: Running unit tests
          command: |
            make lint test
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/deislabs/smi-metrics
    steps:
      - checkout
      - setup_remote_docker:
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: docker build & push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make push
      - add_ssh_keys:
          fingerprints:
            - "b1:b2:ec:ca:62:80:ec:5b:5c:cd:0c:de:ba:91:fc:bf"
      - run:
          name: pushing docker image and creating github release
          command: |
            tag=$(semantics --output-tag)
            if [ $tag ]; then
              COMMIT=$(echo $CIRCLE_SHA1 | cut -c -7)
              docker tag tarunpothulapati/smi-metrics:$COMMIT tarunpothulapati/smi-metrics:$tag
              docker push tarunpothulapati/smi-metrics:$tag
              env GO111MODULE=on make vendor
              make binaries
              cd dist/ && gzip *
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag ./
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - release:
          context: DOCKER_USER
          requires:
            - build
          filters:
            branches:
              only: release