name: Release
on:
  pull_request: {}
  push:
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    branches:
    - master
jobs:
  go_dependencies:
    name: Go dependencies
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Release
      run: |
        make release
